CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(50) UNIQUE NOT NULL,
  barcode VARCHAR(100) UNIQUE,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  category VARCHAR(100),
  brand VARCHAR(100),
  unit VARCHAR(20) DEFAULT 'pcs',
  cost_price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  selling_price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  vat_rate DECIMAL(5, 2) DEFAULT 16.00,
  is_vat_inclusive BOOLEAN DEFAULT FALSE,
  quantity_in_stock INT DEFAULT 0,
  reorder_level INT DEFAULT 0,
  max_stock_level INT DEFAULT 1000,
  is_active BOOLEAN DEFAULT TRUE,
  is_service BOOLEAN DEFAULT FALSE,
  image_url VARCHAR(500),
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id),
  INDEX idx_sku (sku),
  INDEX idx_barcode (barcode),
  INDEX idx_category (category),
  INDEX idx_name (name),
  INDEX idx_active (is_active)
);
