CREATE TABLE IF NOT EXISTS sales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sale_number VARCHAR(50) UNIQUE NOT NULL,
  customer_id INT NOT NULL,
  cashier_id INT NOT NULL,
  sale_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  vat_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(12, 2) DEFAULT 0.00,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  amount_paid DECIMAL(12, 2) DEFAULT 0.00,
  change_amount DECIMAL(12, 2) DEFAULT 0.00,
  payment_method ENUM('cash', 'mpesa', 'card', 'credit') NOT NULL DEFAULT 'cash',
  payment_reference VARCHAR(100),
  status ENUM('pending', 'completed', 'cancelled', 'refunded') DEFAULT 'completed',
  notes TEXT,
  receipt_printed BOOLEAN DEFAULT FALSE,
  is_synced BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customers(id),
  FOREIGN KEY (cashier_id) REFERENCES users(id),
  INDEX idx_sale_number (sale_number),
  INDEX idx_customer (customer_id),
  INDEX idx_cashier (cashier_id),
  INDEX idx_date (sale_date),
  INDEX idx_status (status)
);
