CREATE TABLE IF NOT EXISTS purchases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  purchase_number VARCHAR(50) UNIQUE NOT NULL,
  supplier_id INT NOT NULL,
  user_id INT NOT NULL,
  purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expected_date DATE,
  subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  vat_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(12, 2) DEFAULT 0.00,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  amount_paid DECIMAL(12, 2) DEFAULT 0.00,
  status ENUM('pending', 'ordered', 'received', 'cancelled') DEFAULT 'pending',
  payment_status ENUM('unpaid', 'partial', 'paid') DEFAULT 'unpaid',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_purchase_number (purchase_number),
  INDEX idx_supplier (supplier_id),
  INDEX idx_user (user_id),
  INDEX idx_date (purchase_date),
  INDEX idx_status (status)
);
